version: "3"

services:
  app:
    build:
      context: ./docker
      dockerfile: queue-tuts-01.dockerfile
    container_name: queue-app
    volumes:
      - ./:/home
    command: "tail -f /dev/null"
    networks:
      - default

  queue:
    image: rabbitmq:3-management
    container_name: queue-rabbit
    depends_on:
      - app
    networks:
      - default
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbit
#      RABBITMQ_DEFAULT_PASS: mq
    ports:
      - "15672:15672"

networks:
  default: